name: Deploy Website

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 15
          
      - name: Install
        run: yarn --frozen-lockfile
        
      - name: Build
        run: yarn build
        env:
          GITHUB_PAGES: true
          
      - name: Export
        run: |
          yarn export
          touch ./out/.nojekyll
          cp CNAME out/
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
           
